import { API_BASE_URL, apiRequest } from "./api";

export interface ChatMessage {
  id: string;
  role: "user" | "ai";
  content: string;
  timestamp: Date;
}

const toNumber = (value: unknown) => Number(value) || 0;

export const callGemini = async (chatMessages: ChatMessage[]): Promise<string> => {
  const apiKey = "AQ.Ab8RN6LuIhl420ICyO6seehejWVtzNKGto3zllM4g9haYTNrAA";
  const model = "gemini-3.5-flash";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  // Fetch live database context in background for full access
  let dbContext = "No database context loaded.";
  try {
    const readJson = async (endpoint: string) => {
      const response = await apiRequest(endpoint).catch(() => null);
      return response?.ok ? response.json() : null;
    };

    const [invoices, purchases, payrolls, balanceSheets, bookkeeping] = await Promise.all([
      readJson(`${API_BASE_URL}/invoice/all?limit=100`),
      readJson(`${API_BASE_URL}/purchase-invoice/all`),
      readJson(`${API_BASE_URL}/payroll/all`),
      readJson(`${API_BASE_URL}/balance`),
      readJson(`${API_BASE_URL}/bookkeeping/all`),
    ]);

    const bookkeepingEntries = Array.isArray(bookkeeping?.entries) ? bookkeeping.entries : [];
    const invoicesList = Array.isArray(invoices?.invoices) ? invoices.invoices : [];
    const purchasesList = Array.isArray(purchases?.invoices) ? purchases.invoices : [];
    const payrollList = Array.isArray(payrolls) ? payrolls : [];
    const balanceList = Array.isArray(balanceSheets) ? balanceSheets : [];

    dbContext = `
=== BOOKKEEPING ENTRIES ===
${bookkeepingEntries.map((e: any) => `- Date: ${e.date}, Type: ${e.type}, Category: ${e.category}, Description: ${e.description}, Amount: ₹${e.amount}`).join("\n")}

=== INVOICES ===
${invoicesList.map((i: any) => `- Number: ${i.invoiceNumber}, Client: ${i.customerName}, Date: ${i.invoiceDate}, Status: ${i.status}, Total: ₹${i.grandTotal}`).join("\n")}

=== PURCHASE INVOICES ===
${purchasesList.map((p: any) => `- Date: ${p.createdAt || p.billDate}, Vendor: ${p.partyName || "Unknown Vendor"}, Total: ₹${p.total || 0}`).join("\n")}

=== PAYROLL RECORDS ===
${payrollList.map((pr: any) => `- Employee: ${pr.employeeName}, Gross Salary: ₹${pr.grossSalary}, Net Salary: ₹${pr.netSalary}, Status: ${pr.status}, Date: ${pr.createdAt}`).join("\n")}

=== BALANCE SHEETS ===
${balanceList.slice(0, 5).map((bs: any) => `- Date: ${bs.createdAt}, Assets: ₹${bs.totalAssets}, Liabilities: ₹${bs.totalLiabilities}, Equity: ₹${bs.equity}`).join("\n")}
`;
  } catch (err) {
    console.error("Error loading database context for Gemini:", err);
  }

  // Filter out any "Thinking..." placeholder and format messages
  const contents = chatMessages
    .filter(msg => msg.content !== "Thinking...")
    .map(msg => ({
      role: msg.role === "user" ? "user" : "model",
      parts: [{ text: msg.content }]
    }));

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents,
      systemInstruction: {
        parts: [{ text: `You are SHREE ANDAL AI Assistant, a helpful financial AI assistant for SHREE ANDAL AI SOFTWARE SOLUTIONS. You have FULL access to the user's real-time business database and modules.

Here is the current business database state:
${dbContext}

Answer questions politely, concisely, and helpfully. If the user asks about the database data, calculate or report metrics using this state. If the user asks about the software, you can mention features like Payroll Automation, Tax & GST, Balance Sheet, Profit & Loss, Cash Flow Prediction, Financial Ratios, Bookkeeping, Inventory Management, Bank Reconciliation, Fraud Detection, Civil Engineering, and Invoice Automation.` }]
      }
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    console.error("Gemini API error details:", errorData);
    throw new Error(errorData.error?.message || `Gemini API Error: ${response.statusText}`);
  }

  const data = await response.json();
  const replyText = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!replyText) {
    throw new Error("No response generated by Gemini.");
  }

  return replyText;
};
